import type { NextPage } from "next";
import Hero from "../components/landing/Hero";
import Head from "next/head";
import Navbar from "../components/landing/Navbar";
import History from "../components/landing/History";
import Review from "../components/landing/Review";
import Location from "../components/landing/Location";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Junior Webmaster Camp 12</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary w-full h-fit relative py-10">
        <Navbar />
        <Hero />
        <History />
        <Review />
        <Location />
      </div>
    </div>
  );
};

export default Home;
